baseurl = "/"
languageCode = "en-us"
title = "Truck Stop Coffee"
theme = "blackburn"
author = "Sarah Allen Reed"
copyright = "All work written by Sarah Allen Reed."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
    ordered = false

[params]
  # Shown in the home page
  title = "Truck Stop Coffee"
  subtitle = "A Ramblin' Collection Of Foolishness From A Wanderin' Cartoonist-Errant"
  brand = "truck stop coffee"
  # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  # highlightjs = "androidstudio"
  dateFormat = "Jan 02 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "topics"
    url = "/tags/"
  [[menu.main]]
    name = "Photo Roll"
    pre = "<i class='fa fa-camera fa-fw'></i>"
    weight = 4
    identifier = "photos"
    url = "/tags/photo-roll"
  [[menu.main]]
    name = "About Me"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 6
    identifier = "about"
    url = "/post/about"
  [[menu.main]]
    name = "FAQ"
    pre = "<i class='fa fa-question fa-fw'></i>"
    weight = 7
    identifier = "faq"
    url = "/post/faq"
  [[menu.main]]
    name = "Links"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 7
    identifier = "links"
    url = "/post/links"
 [[menu.main]]
   name = "Main Site"
   pre = "<i class='fa fa-home fa-fw'></i>"
   weight = 9
   url = "http://sarahallenreed.com"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  # twitter="*"
  # gnusocial="*"
  # facebook="*"
  # weibo="*"
  # tumblr="*"
  # instagram="*"
  # flickr="*"
  # photo500px="*"
  # pinterest="*"
  # youtube="*"
  # vimeo="*"
  # vine="*"
  # slideshare="*"
  # linkedin="*"
  # xing="*"
  # reddit="*"
  # hackernews="*"
  # github=""
  # gitlab="*"
  # bitbucket="*"
  # stackoverflow="*"
  # serverfault="*"
  # steam="*"
  # mobygames="*"
  # lastfm="*"
  # discogs="*"
  # keybase="*"


[markup.goldmark.renderer]
  unsafe= true
[markup.goldmark.extensions]
  table = true