baseurl = "/"
languageCode = "en-us"
title = "Truck Stop Coffee"
theme = "blackburn"
author = "Piper Bly "
copyright = "All work written by Piper Bly ."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
    ordered = false
    

[params]
  # Shown in the home page
  title = "Truck Stop Coffee"
  subtitle = "A Ramblin' Collection Of Foolishness From A Wanderin' Cartoonist-Errant"
  brand = "truck stop coffee"
  # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  # highlightjs = "androidstudio"
  dateFormat = "January 2, 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-coffee fa-fw fa-flip-horizontal' aria-hidden='true'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Topics and Tags"
    pre = "<i class='fa fa-tag fa-fw' aria-hidden='true'></i>"
    weight = 2
    identifier = "topics"
    url = "/tags/"
  [[menu.main]]
    name = "Blog Posts"
    pre = "<i class='fa fa-book fa-fw' aria-hidden='true'></i>"
    weight = 3
    identifier = "post"
    url = "/tags/blogpost"
  [[menu.main]]
    name = "Photo Rolls"
    pre = "<i class='fa fa-camera fa-fw' aria-hidden='true'></i>"
    weight = 4
    identifier = "photos"
    url = "/tags/photo-roll"
  [[menu.main]]
    name = "Project Updates"
    pre = "<i class='fa fa-newspaper fa-fw' aria-hidden='true'></i>"
    weight = 4
    identifier = "updates"
    url = "/post/updates"
  [[menu.main]]
    name = "Miscellany"
    pre = "<i class='fa fa-umbrella fa-fw'></i>"
    weight = 5
    identifier = "misc"
    url = "/post/misc"
  [[menu.main]]
    name = "About Me"
    pre = "<i class='fa fa-user fa-fw' aria-hidden='true'></i>"
    weight = 6
    identifier = "about"
    url = "/post/about"
  [[menu.main]]
    name = "FAQ"
    pre = "<i class='fa fa-question fa-fw'></i>"
    weight = 7
    identifier = "faq"
    url = "/post/faq"
  [[menu.main]]
    name = "Links"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 7
    identifier = "links"
    url = "/post/links"
 [[menu.main]]
   name = "Main Site"
   pre = "<i class='fa fa-home fa-fw'></i>"
   weight = 9
   url = "http://sarahallenreed.com"

[markup.goldmark.renderer]
  unsafe= true
[markup.goldmark.extensions]
  table = true
[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false
